<?php

namespace App\DataFixtures;

use App\Entity\CCP;
use App\Entity\Competence;
use App\Entity\Module;
use App\Entity\Objectif;
use App\Entity\TitreProfessionnel as EntityTitreProfessionnel;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class TitreProfessionnel extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $titre = new EntityTitreProfessionnel();
        $titre->setSigle('CDA');
        $titre->setDateApplication(date_create('2020-02-01'));
        $titre->setNom('Concepteur Développeur d\'application Mobile');
        $titre->setIsActif(1);
        $titre->addCcp($ccp = new CCP, [
            $ccp->setNom('CCP 1 : Concevoir et développer des composants d\'interface utilisateur en intégrant les recommandations de sécurité'),
            $ccp->setIsTranverse(false),
            $ccp->setTitreProfessionnel(null),
            $ccp->setOrdreAffichage("1"),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Maquetter une application'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("1"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Maquettage'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Concevoir la maquette d’une application adaptée à l’équipement ciblé'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser les enchaînements des interfaces'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Utiliser un outil de maquettage'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Développer une interface utilisateur de type desktop'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("2"),
                $competence->addModule($module = new Module, [
                    $module->setNom('ElectronJS'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Identifier les différences entre une application web et une application Desktop'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Maîtriser l’architecture d’ElectronJS'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Réaliser une application desktop avec ElectronJS'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Développer des composants d’accès aux données'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("3"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Javascript - Ajax - Jquery'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Maîtriser le langage JavaScript'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Manipuler le DOM'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Manipuler les API JavaScript HTML5'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Mettre en œuvre jQuery pour les échanges Ajax'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $manager->persist($ccp),
        ]);$titre->addCcp($ccp = new CCP, [
            $ccp->setNom('CCP 2 : Concevoir et développer la persistance des données en intégrant les recommandations de sécurité '),
            $ccp->setIsTranverse(false),
            $ccp->setTitreProfessionnel(null),
            $ccp->setOrdreAffichage("2"),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Concevoir une base de données'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("1"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Conception de base de données'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Concevoir une base de données d’un point de vue conceptuel'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser le MCD (Modèle Conceptuel de Données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('En déduire le MLD (Modèle Logique de données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser et optimiser le MPD (Modèle Physique de Données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $manager->persist($ccp),
        ]);$titre->addCcp($ccp = new CCP, [
            $ccp->setNom('CCP 3 : Concevoir et développer une appli multicouche répartie en intégrant les recommandations de sécurité'),
            $ccp->setIsTranverse(false),
            $ccp->setTitreProfessionnel(null),
            $ccp->setOrdreAffichage("3"),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Collaborer à la gestion d’un projet informatique et à l’organisation de l\'environnement de développement '),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("1"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Culture numérique / Gestion de projet'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Appréhender les enjeux d’un projet informatique'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Identifier les acteurs d’un projet'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Identifier les différents modèles de gestion de projets'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Gestion de projet Agile (SCRUM)'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("2"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Appliquer les principes et valeurs de l’agilité'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Participer, en tant qu’équipier à un projet Scrum'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Passer la certification PSM I de Scrum.org'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Concevoir une application'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("2"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Conception Orientés Objet '),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Choisir un patron de conception face à une problématique'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Mettre en œuvre un patron de conception'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('UML'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("2"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Établir les diagrammes UML pour modéliser les besoins exprimés dans un cahier des charges'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Choisir les diagrammes UML à établir à chaque phase du projet'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Exploiter toutes les possibilités du diagramme de classes'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Développer des composants métier'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("3"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Java SE'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Développer des classes Java'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Utiliser les principaux mots clefs du langage Java '),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Concevoir des applications Java en console'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Web services - Java'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("2"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Maîtriser l’architecture REST et son implémentation en Java'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Consommer des Web Services existants'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Développer et déployer des Web Services'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $manager->persist($ccp),
        ]);
        $manager->persist($titre);


        $titre = new EntityTitreProfessionnel();
        $titre->setSigle('DWWM');
        $titre->setDateApplication(date_create('2020-02-01'));
        $titre->setNom('Développeur Web et Web Mobile');
        $titre->setIsActif(1);
        $titre->addCcp($ccp = new CCP, [
            $ccp->setNom('CCP 1 : Développer la partie front-end d\'une application web ou web mobile en intégrant les recommandations de sécurité'),
            $ccp->setIsTranverse(false),
            $ccp->setTitreProfessionnel(null),
            $ccp->setOrdreAffichage("1"),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Maquetter une application'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("1"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Maquettage'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Concevoir la maquette d’une application adaptée à l’équipement ciblé'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser les enchaînements des interfaces'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Utiliser un outil de maquettage'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Réaliser une interface utilisateur web statique et adaptable'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("2"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Web statique (HTML/CSS/Bootsrap)'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Construire des documents valides dans un langage de balises'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Créer des pages web statiques, adaptées à l’équipement ciblé'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Développer et déboguer un site web'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Développer une interface utilisateur web dynamique'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("3"),
                $competence->addModule($module = new Module, [
                    $module->setNom('JavaScript'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Maîtriser le langage JavaScript'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Manipuler le DOM'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Manipuler les API JavaScript HTML5'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Mettre en œuvre jQuery pour les échanges Ajax'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Les bases d’Angular'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("2"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Développer en TypeScript'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Créer une première application Angular. '),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Utiliser les composants, Directives et Pipes'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Angular avancé'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("3"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Personnaliser l’affichage'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Programmer de manière réactive et asynchrone'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('De tester et de déployer une application'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $manager->persist($ccp),
        ]);
        $titre->addCcp($ccp = new CCP, [
            $ccp->setNom('CCP 2 : Développer la partie back-end d\'une application web ou web mobile en intégrant les recommandations de sécurité'),
            $ccp->setIsTranverse(false),
            $ccp->setTitreProfessionnel(null),
            $ccp->setOrdreAffichage("2"),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Créer une base de données'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("1"),
                $competence->addModule($module = new Module, [
                    $module->setNom('PHP Approche Procédurale'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Installer et configurer l’environnement de développement PHP'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Développer des algorithmes simples en PHP procédural'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Déboguer un programme PHP'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('PHP Orienté Objet'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("2"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Créer, Référencer et instancier des classes en PHP'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Construire un modèle de données Objet'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Développer des pages PHP en utilisant le MVC'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Symfony'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("3"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Maîtriser l’architecture du framework Symfony'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Utiliser les templates Twig,'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Utiliser Doctrine pour la persistance des données'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Développer les composants d\'accès aux données'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("2"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Conception de base de données'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Concevoir une base de données d’un point de vue conceptuel'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser le MCD (Modèle Conceptuel de Données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('En déduire le MLD (Modèle Logique de données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser et optimiser le MPD (Modèle Physique de Données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Développer la partie back-end d\'une application web ou web mobil'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("3"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Conception de base de données'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Concevoir une base de données d’un point de vue conceptuel'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser le MCD (Modèle Conceptuel de Données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('En déduire le MLD (Modèle Logique de données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Formaliser et optimiser le MPD (Modèle Physique de Données)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $manager->persist($ccp),
        ]);
        $titre->addCcp($ccp = new CCP, [
            $ccp->setNom('Compétences transverses'),
            $ccp->setIsTranverse(true),
            $ccp->setTitreProfessionnel(null),
            $ccp->setOrdreAffichage("3"),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Professionnalisation'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("1"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Professionnalisation'),
                    $module->setIsTre(true),
                    $module->setExamen(false),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Rédiger un CV et une lettre de motivation contextualisés'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Communiquer efficacement avec un recruteur avant, pendant et après les entretiens de recrutement'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Organiser sa recherche de stages et d’emploi'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Appréhender la laïcité dans un contexte professionnel'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Culture numérique / veille'),
                    $module->setIsTre(false),
                    $module->setExamen(false),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("2"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Identifier les différents métiers de l’informatique et du numérique'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Identifier les types d’entreprises susceptibles d’employer des développeurs web'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Comprendre les exigences du métier en terme de veille technologique'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $competence->addModule($module = new Module, [
                    $module->setNom('Gestion de projet Agile'),
                    $module->setIsTre(false),
                    $module->setExamen(true),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("3"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Appliquer les principes et valeurs de l’agilité'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Participer, en tant qu’équipier à un projet Scrum'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Passer la certification PSM I de Scrum.org (facultatif)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $ccp->addCompetence($competence = new Competence, [
                $competence->setNom('Langue'),
                $competence->setCcp(null),
                $competence->setOrdreAffichage("2"),
                $competence->addModule($module = new Module, [
                    $module->setNom('Anglais'),
                    $module->setIsTre(false),
                    $module->setExamen(false),
                    $module->setCompetence(null),
                    $module->setOrdreAffichage("1"),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Lire une documentation technique en anglais'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("1"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Rédiger un email technique en anglais'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("2"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Commenter son code source en anglais'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("3"),
                        $manager->persist($objectif),
                    ]),
                    $module->addObjectif($objectif = new Objectif, [
                        $objectif->setNom('Passer le TOEIC (facultatif)'),
                        $objectif->setModule(null),
                        $objectif->setOrdreAffichage("4"),
                        $manager->persist($objectif),
                    ]),
                    $manager->persist($module),
                ]),
                $manager->persist($competence),
            ]),
            $manager->persist($ccp),
        ]);
        $manager->persist($titre);

        $manager->flush();
    }
}
